// Code generated by mockery v2.44.1. DO NOT EDIT.

package usecasemock

import (
	context "context"
	domain "task-manager/Domain"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// TaskUsecase is an autogenerated mock type for the TaskUsecase type
type TaskUsecase struct {
	mock.Mock
}

// AddTask provides a mock function with given fields: c, task
func (_m *TaskUsecase) AddTask(c context.Context, task domain.Task) *domain.AppError {
	ret := _m.Called(c, task)

	if len(ret) == 0 {
		panic("no return value specified for AddTask")
	}

	var r0 *domain.AppError
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) *domain.AppError); ok {
		r0 = rf(c, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AppError)
		}
	}

	return r0
}

// DeleteTask provides a mock function with given fields: c, id, userid, isadmin
func (_m *TaskUsecase) DeleteTask(c context.Context, id string, userid string, isadmin bool) *domain.AppError {
	ret := _m.Called(c, id, userid, isadmin)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 *domain.AppError
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *domain.AppError); ok {
		r0 = rf(c, id, userid, isadmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AppError)
		}
	}

	return r0
}

// GetAllTasks provides a mock function with given fields: c, isadmin, userid
func (_m *TaskUsecase) GetAllTasks(c context.Context, isadmin bool, userid primitive.ObjectID) ([]domain.Task, *domain.AppError) {
	ret := _m.Called(c, isadmin, userid)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 []domain.Task
	var r1 *domain.AppError
	if rf, ok := ret.Get(0).(func(context.Context, bool, primitive.ObjectID) ([]domain.Task, *domain.AppError)); ok {
		return rf(c, isadmin, userid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool, primitive.ObjectID) []domain.Task); ok {
		r0 = rf(c, isadmin, userid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool, primitive.ObjectID) *domain.AppError); ok {
		r1 = rf(c, isadmin, userid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.AppError)
		}
	}

	return r0, r1
}

// GetTask provides a mock function with given fields: c, id, isadmin, userid
func (_m *TaskUsecase) GetTask(c context.Context, id string, isadmin bool, userid string) (domain.Task, *domain.AppError) {
	ret := _m.Called(c, id, isadmin, userid)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 domain.Task
	var r1 *domain.AppError
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, string) (domain.Task, *domain.AppError)); ok {
		return rf(c, id, isadmin, userid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, string) domain.Task); ok {
		r0 = rf(c, id, isadmin, userid)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool, string) *domain.AppError); ok {
		r1 = rf(c, id, isadmin, userid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.AppError)
		}
	}

	return r0, r1
}

// SetTask provides a mock function with given fields: c, id, updatedTask, isadmin
func (_m *TaskUsecase) SetTask(c context.Context, id string, updatedTask domain.Task, isadmin bool) *domain.AppError {
	ret := _m.Called(c, id, updatedTask, isadmin)

	if len(ret) == 0 {
		panic("no return value specified for SetTask")
	}

	var r0 *domain.AppError
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Task, bool) *domain.AppError); ok {
		r0 = rf(c, id, updatedTask, isadmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AppError)
		}
	}

	return r0
}

// NewTaskUsecase creates a new instance of TaskUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUsecase {
	mock := &TaskUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
