// Code generated by mockery v2.44.1. DO NOT EDIT.

package repomocks

import (
	domain "task-manager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: id
func (_m *UserRepository) DeleteUser(id string) *domain.AppError {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 *domain.AppError
	if rf, ok := ret.Get(0).(func(string) *domain.AppError); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AppError)
		}
	}

	return r0
}

// LoginUserDb provides a mock function with given fields: user
func (_m *UserRepository) LoginUserDb(user domain.User) (string, interface{}, *domain.AppError) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for LoginUserDb")
	}

	var r0 string
	var r1 interface{}
	var r2 *domain.AppError
	if rf, ok := ret.Get(0).(func(domain.User) (string, interface{}, *domain.AppError)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(domain.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(domain.User) interface{}); ok {
		r1 = rf(user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(interface{})
		}
	}

	if rf, ok := ret.Get(2).(func(domain.User) *domain.AppError); ok {
		r2 = rf(user)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*domain.AppError)
		}
	}

	return r0, r1, r2
}

// RegisterUserDb provides a mock function with given fields: user
func (_m *UserRepository) RegisterUserDb(user domain.User) *domain.AppError {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUserDb")
	}

	var r0 *domain.AppError
	if rf, ok := ret.Get(0).(func(domain.User) *domain.AppError); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AppError)
		}
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
